### ISSUE TITLE
initial state not set for string

### ISSUE THREAD

**Issue by nasimzf** [DNA-and-Natural-Algorithms-Group/multistrand#30]
In the function   genUntilConvergenceWithInitialState  , I put this statement "        print "builderRate.initial_states " , builderRate.initial_states"  before calling   currTime = builderRate.averageTimeFromInitial().

If I run "python test_string_method.py morrison0 100 0.01 " ,  the result is 
builderRate.initial_states  {"('65:auto_65', (0, 0, 0, 0, 0, 0, 0, 0, 0, 0))('66:auto_66', (0, 0, 0, 0, 0, 0, 0, 0, 0, 0))": Count: 3  flux: 777777}

If I run python test_string_method.py morrison0 4 0.01, the results is : 
builderRate.initial_states  {}  
and I get an error : in weightedPassageTime
    return sumTime / sumStart
ZeroDivisionError: float division by zero

In both cases, the initial state seems not to be correct. Could you please tell me if if I'm misunderstanding the test_string_method?

**Comment by fdannenberg** [comment]
The current copy of test_string_method is a hybridization example. The initial state has the right structure. The division error occurs because sometimes no initial states are connected to the final states, which can only occur for the pathway elaboration. I adjusted the code to assert an error, now pushed.
